server:
  port: 8014
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.101.65:8848
      discovery:
        namespace: 051bbfcf-adda-4fdd-9fbd-35676e1ac4c7
    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/**
